### PR TITLE
5.0.0 events and less strict dependency constraint on logstash-core-plugin-api

### PR DESCRIPTION
**Pull request by algestam**
Updated plugin to use 5.0 events and changed dependency constrain on logstash-core-plugin-api so that the plugin can be installed on logstash v5.0.0-alpha3 and later.

### CODE REVIEW

**Comment by algestam** [comment]
I have tested the code locally and it works ok for me and all rspec tests passes. However, the Travis CI build fails with this error which I don't really understand:

    LoadError: JRuby ext built for wrong Java version in `JrubyEventExtService': java.lang.UnsupportedClassVersionError: JrubyEventExtService : Unsupported major.minor version 52.0

It seems to be some sort of Java class mismatch. Can it be that some dependency (or the plugin itself) has been compiled with a JDK 1.8 but it is running in a JDK 1.7 environment?

**Comment by wiibaa** [comment]
@algestam thanks for your efforts to update the plugin. Can you please change the content of the .travis.yml file with what is described in https://github.com/elastic/logstash/issues/5811 this will make the CI happy

**Comment by algestam** [comment]
Thanks @wiibaa for the help! I have updated .travis.yml according to elastic/logstash#5811 and the build was successful :)

**Comment by wiibaa** [comment]
LGTM
@logstash-plugins/logstash-core need merge && publish please

**Pull request closed without merging**
