### PR TITLE
Refactor: leverage scheduler mixin

### PR DESCRIPTION
**Pull request by kares**
#### part of https://github.com/elastic/logstash/issues/13773

see https://github.com/logstash-plugins/logstash-mixin-scheduler/pull/1

### CODE REVIEW

**Review by andsel — APPROVED** [review]
LGTM

**Comment by nicpenning** [comment]
Greetings! Any chance this commit can cause a large YML file from not being parsed?

I can't get past Logstash 8.3.2 because of the translate filter issue:

```
[2023-04-05T11:06:21,961][ERROR][logstash.javapipeline    ][timberlorry-filebeat-dhcp] Pipeline error {:pipeline_id=>"timberlorry-filebeat-dhcp", :exception=>#<LogStash::Filters::Dictionary::DictionaryFileError: Translate: The incoming YAML document exceeds the limit: 3145728 code points. when loading dictionary file at C:\ProgramData\elastic\universalConfig\dhcp_enrich.yml>
```
Our YAML file has 23559 lines and is 3,831,983 characters long.

I am unsure what a code point is, but I am unsure what else to do at this point.

**Comment by andsel** [comment]
Hi @nicpenning 
this change regards only the usage of a utility gem that exposes the same scheduler functionality across all the Logstash plugins. 
So I don't think it relates directly to your issue.
Please open a bug report with a reproducer of your use case, specifying your pipeline config at least of the interested part; and if you are using a `yaml` as dictionary that is functional to manifest the problem, please attach it.

Please do not comment on closed/merged PRs, prefer to open a new issue, and tag me in that please.

**Comment by mashhurs** [comment]
@nicpenning , it sounds your `snakeyaml` dependency somehow updated. Logstash `v8.3.2` uses `1.29` which should not limit 3M. Snakeyaml introduced this limit from `1.32` (reference: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes)
See my recent change to [logstash-filter-useragent](https://github.com/logstash-plugins/logstash-filter-useragent/pull/84/files#diff-727eadc8233c4746abdda0db24907200515ac333670f48fd0e8e9288374510a9R51) to figure out more on what is happening.

**Comment by nicpenning** [comment]
I did find the correct issue and posted there. I can move away from the discussion, thank you!

**Comment by nicpenning** [comment]
@mashhurs found my issue here: https://github.com/logstash-plugins/logstash-filter-translate/issues/96

**Pull request merged**
